ci: Add additional check before release

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -54,11 +54,19 @@ jobs:
       # ------------------------------------------------------------------------
       # Publishing & draft release.
 
-      - name: Check version equality
+      - name: Check version equality between Poetry and __version__
         run: |
           pattern="__version__ = \"$(poetry version --short)\""
           if ! grep -q -R -F --include="__init__.py" "$pattern" src; then
-            echo "::error::Version set with Poetry does not match __version__ variable."; exit 1
+            echo "::error::No version equality between Poetry and __version__."; exit 1
+          fi
+
+      - name: Check version equality between Poetry and Git tag
+        run: |
+          poetry_version=$(poetry version --short)
+          git_tag=${GITHUB_REF#refs/*/}
+          if [[ "v$poetry_version" != "$git_tag" ]]; then
+            echo "::error::No version equality between Poetry and Git tag."; exit 1
           fi
 
       - name: Publish to PyPI with Poetry
diff --git a/.github/workflows/testpypi.yaml b/.github/workflows/testpypi.yaml
--- a/.github/workflows/testpypi.yaml
+++ b/.github/workflows/testpypi.yaml
@@ -64,11 +64,11 @@ jobs:
           pversion="$(poetry version --short)"
           sed -i "/^__version__/c\__version__ = \"$pversion\"" src/*/__init__.py
 
-      - name: Check version equality
+      - name: Check version equality between Poetry and __version__
         run: |
           pattern="__version__ = \"$(poetry version --short)\""
           if ! grep -q -R -F --include="__init__.py" "$pattern" src; then
-            echo "::error::Version set with Poetry does not match __version__ variable."; exit 1
+            echo "::error::No version equality between Poetry and __version__."; exit 1
           fi
 
       - name: Configure Poetry repo for TestPyPI
